"""Assemble a self-contained HyperFrames project per cut: build/out/<project>-16x9 and -9x16.
The engine is inlined into the page (HyperFrames looks for the timeline registration in the page itself)."""
import json, shutil
from .common import ROOT, CUTS

HF_VERSION = json.loads((ROOT / "package.json").read_text(encoding="utf-8"))["hyperframesVersion"]


def _css_vars(p):
    pal, f = p.data["palette"], p.data.get("fonts", {})
    v = {"primary": pal["primary"], "primary2": pal.get("primary2", pal["primary"]), "secondary": pal.get("secondary", pal["primary"]),
         "accent": pal["accent"], "ink": pal["ink"], "ink2": pal.get("ink2", pal["ink"]), "paper": pal["paper"], "good": pal.get("good", "#16a34a"),
         "bad": pal.get("bad", "#e5484d"), "grad": pal.get("grad", f"linear-gradient(100deg,{pal['primary']},{pal['accent']})"),
         "f-title": f"'{f.get('title', 'DM Sans')}'", "f-body": f"'{f.get('body', 'Nunito')}'", "f-note": f"'{f.get('note', 'Caveat')}'"}
    return ";".join(f"--{k}:{val}" for k, val in v.items())


def build(p, cut):
    w, h, tag = CUTS[cut]
    B = json.loads((p.build / f"beats-{cut}.json").read_text(encoding="utf-8"))
    d = p.out_dir(cut)
    if d.exists():
        shutil.rmtree(d / "assets", ignore_errors=True)
    (d / "assets" / "audio").mkdir(parents=True, exist_ok=True)
    scenes = "\n".join(f'  <section class="scene" id="{s["id"]}"></section>' for s in B["scenes"])
    # transition clips (generated by `studio.py transitions`), laid over the scene boundary
    trans, starts = [], {s["id"]: s["start"] for s in B["scenes"]}
    for t in p.data.get("transitions", []):
        clip = p.gen / "transitions" / f"{t['id']}-{tag}.mp4"
        if not t.get("enabled", True) or t["scene"] not in starts or not clip.exists():
            continue
        dur = float(t.get("seconds", 1.2)); s0 = starts[t["scene"]]
        t0 = {"before": s0 - dur, "center": s0 - dur / 2}.get(t.get("align", "center"), s0)
        (d / "assets" / "transitions").mkdir(exist_ok=True)
        shutil.copy(clip, d / "assets" / "transitions" / clip.name)
        trans.append(f'  <video id="tr-{t["id"]}" class="transition clip" data-start="{max(0, t0):.3f}" data-duration="{dur:.3f}" data-track-index="{5 + len(trans)}" muted playsinline src="assets/transitions/{clip.name}"></video>')
    tpl = (ROOT / "engine" / "template.html").read_text(encoding="utf-8")
    html = (tpl.replace("{{TITLE}}", f"{p.data['name']} ({cut})").replace("{{CUT}}", cut).replace("{{W}}", str(w)).replace("{{H}}", str(h))
               .replace("{{WW}}", str(round(w * 1.7))).replace("{{DUR}}", str(B["duration"])).replace("{{SCENES}}", scenes)
               .replace("{{TRANSITIONS}}", "\n".join(trans)).replace("{{CSS_VARS}}", _css_vars(p))
               .replace("{{PROJECT_JSON}}", json.dumps({k: p.data.get(k) for k in ("name", "brand", "palette", "backgrounds", "solids", "pose_aspect", "scenes")}))
               .replace("{{ENGINE}}", (ROOT / "engine" / "scenes.js").read_text(encoding="utf-8")))
    (d / "index.html").write_text(html, encoding="utf-8")
    (d / "package.json").write_text(json.dumps({"private": True, "hyperframesVersion": HF_VERSION}, indent=1), encoding="utf-8")
    shutil.copy(p.build / f"beats-{cut}.js", d / "beats.js")
    gsap = ROOT / "node_modules" / "gsap" / "dist" / "gsap.min.js"
    if not gsap.exists():
        raise SystemExit("node_modules/gsap is missing. Run `npm install` in the repo root.")
    shutil.copy(gsap, d / "assets" / "gsap.min.js")
    fonts = p.dir / "fonts" if (p.dir / "fonts" / "fonts.css").exists() else ROOT / "assets" / "fonts"
    shutil.copytree(fonts, d / "assets" / "fonts")
    for sub in ("brand", "poses", "images"):
        if (p.dir / sub).exists():
            shutil.copytree(p.dir / sub, d / "assets" / "project" / sub, ignore=shutil.ignore_patterns("src", "*.psd"))
    shutil.copy(p.build / f"mix-{cut}.wav", d / "assets" / "audio" / "mix.wav")
    print(f"  page {cut}: {d}")
    return d
